### ISSUE TITLE
Add output string preview in Translate (NYJY) node

### ISSUE THREAD

**Issue by pandayummy** [aidenli/ComfyUI_NYJY#10]
![image](https://github.com/user-attachments/assets/8aff55d4-43d8-4904-b03c-8d6836923e3f)

Can we have a preview of the translated/ output string below the box? like what WD does.
https://github.com/pythongosssss/ComfyUI-WD14-Tagger?tab=readme-ov-file

**Comment by pandayummy** [comment]
add a **Skip Translation** toggle button in case of internet problem.

![image](https://github.com/user-attachments/assets/ddb79c0f-2282-48c1-bae4-9234a3bc2615)

**Comment by aidenli** [comment]
> ![image](https://private-user-images.githubusercontent.com/32961592/371386400-8aff55d4-43d8-4904-b03c-8d6836923e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4Nzg0MDQsIm5iZiI6MTcyNzg3ODEwNCwicGF0aCI6Ii8zMjk2MTU5Mi8zNzEzODY0MDAtOGFmZjU1ZDQtNDNkOC00OTA0LWIwM2MtOGQ2ODM2OTIzZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE0MDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYjRhNzIyNzgxYjkwYTA5YWIxMGRjYzdiNmZjY2NhMGYyYjBmMTgzYTlkZjhiY2NhMmYyNDdlZmZiOWJhMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lXp7EhBnH7LZCFzhBGklxVjTqKJ0z5WdIJurYCmI2i0)
> 
> Can we have a preview of the translated/ output string below the box? like what WD does. https://github.com/pythongosssss/ComfyUI-WD14-Tagger?tab=readme-ov-file

Good idea, I will add this feature in the next version. Thank you.

**Comment by aidenli** [comment]
> add a **Skip Translation** toggle button in case of internet problem.
> 
> ![image](https://private-user-images.githubusercontent.com/32961592/371834442-ddb79c0f-2282-48c1-bae4-9234a3bc2615.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4Nzg0MDQsIm5iZiI6MTcyNzg3ODEwNCwicGF0aCI6Ii8zMjk2MTU5Mi8zNzE4MzQ0NDItZGRiNzljMGYtMjI4Mi00OGMxLWJhZTQtOTIzNGEzYmMyNjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE0MDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhOWQ5ZTg5ODNmMTRiYzYzMzY3YzYzYTk2ZmJmY2MxYWFlNjExYjI4ZGQ2OGM2MTEyNzgzZjg2ZWJlZGU0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oVTf0txiAF03Oq2_A1z-l_fZsWSDOaPVxZWNVaIV4Qw)

This seems to be a network problem that prevents access to the Google domain.

**Comment by aidenli** [comment]
> ![image](https://private-user-images.githubusercontent.com/32961592/371386400-8aff55d4-43d8-4904-b03c-8d6836923e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTA4ODMsIm5iZiI6MTcyODQ5MDU4MywicGF0aCI6Ii8zMjk2MTU5Mi8zNzEzODY0MDAtOGFmZjU1ZDQtNDNkOC00OTA0LWIwM2MtOGQ2ODM2OTIzZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE2MTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNmE4YzFlNDk2YTMzYzk0YzZkOWEyOTI4OTZkMDdkYjk1MDEwMWUwNjcxMGM3MmNhN2U3Mzc3NTdmMWYzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JOA_Rvm2r4DbWF79o1iZ6lyQ4bdVR3tt4FILvpeSpoI)
> 
> Can we have a preview of the translated/ output string below the box? like what WD does. https://github.com/pythongosssss/ComfyUI-WD14-Tagger?tab=readme-ov-file

I have added a preview area, you can update the project to see it.

**Comment by pandayummy** [comment]
Than you so much!
