### ISSUE TITLE
[Feature Request]: Support New Alpha two Version

### ISSUE THREAD

**Issue by xiongbb** [aidenli/ComfyUI_NYJY#12]
https://huggingface.co/spaces/fancyfeast/joy-caption-alpha-two

The new version adds many options

**Comment by aidenli** [comment]
ComfyUI_LayerStyle(https://github.com/chflame163/ComfyUI_LayerStyle/tree/main) already provides this function, so I won't reinvent the wheel. I provide an online calling node. The advantage is that you don't need to download jaycaotion alpha two, so you need llm and clip models, but the daily quota is limited.

**Comment by GoodGoodstudy0daydayup** [comment]
https://huggingface.co/spaces/fancyfeast/joy-caption-beta-one

The previous newbie mode called joy2, can it now call joy caption beta 1?
