### ISSUE TITLE
我的模型怎么自动下载不了

### ISSUE THREAD

**Issue by mrfuturman** [aidenli/ComfyUI_NYJY#13]
JoyCaption
Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory E:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI_NYJY\../../models/llm/Meta-Llama-3.1-8B-bnb-4bit.

大佬帮我看看，谢谢

**Comment by aidenli** [comment]
你看下控制台，是否因为网络问题没有连接上huggingface.co。
如果是网络问题，你可以手动下载网盘资源（https://pan.quark.cn/s/e2a52f2a5bae），并把模型放到对应的位置。参考说明文档：https://github.com/aidenli/ComfyUI_NYJY/blob/main/docs/joycaption.md
