### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by vigee88** [aidenli/ComfyUI_NYJY#7]
如果我为google翻译设置了代理，然后我关闭代理软件并转换为百度翻译，再次运行此时会提示错误
HTTPConnectionPool(host='127.0.0.1', port=10809): Max retries exceeded with url: http://api.fanyi.baidu.com/api/trans/vip/translate?appid=20230506001667994&q=(,,,,中间省略)&from=en&to=zh&salt=50592&sign=d597dbd7919db3c11e0f194adacaf7c0 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022AFDAD91B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
也就是说这个代理是百度google翻译公用的，而我在config.json删除代理，并重启comfyui之后，仍然同样错误提示。我不得不重装插件，，，

**Comment by aidenli** [comment]
> 如果我为google翻译设置了代理，然后我关闭代理软件并转换为百度翻译，再次运行此时会提示错误 HTTPConnectionPool(host='127.0.0.1', port=10809): Max retries exceeded with url: [http://api.fanyi.baidu.com/api/trans/vip/translate?appid=20230506001667994&q=(,,,,中间省略)&from=en&to=zh&salt=50592&sign=d597dbd7919db3c11e0f194adacaf7c0](http://api.fanyi.baidu.com/api/trans/vip/translate?appid=20230506001667994&q=(,,,,%E4%B8%AD%E9%97%B4%E7%9C%81%E7%95%A5)&from=en&to=zh&salt=50592&sign=d597dbd7919db3c11e0f194adacaf7c0) (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022AFDAD91B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。 也就是说这个代理是百度google翻译公用的，而我在config.json删除代理，并重启comfyui之后，仍然同样错误提示。我不得不重装插件，，，

我在最新版本里面强制了百度的请求不用代理，你可以更新看看是否能解决问题。

**Comment by vigee88** [comment]
> > 如果我为google翻译设置了代理，然后我关闭代理软件并转换为百度翻译，再次运行此时会提示错误 HTTPConnectionPool(host='127.0.0.1', port=10809): Max retries exceeded with url: [http://api.fanyi.baidu.com/api/trans/vip/translate?appid=20230506001667994&q=(,,,,中间省略)&from=en&to=zh&salt=50592&sign=d597dbd7919db3c11e0f194adacaf7c0](http://api.fanyi.baidu.com/api/trans/vip/translate?appid=20230506001667994&q=(,,,,%E4%B8%AD%E9%97%B4%E7%9C%81%E7%95%A5)&from=en&to=zh&salt=50592&sign=d597dbd7919db3c11e0f194adacaf7c0) (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022AFDAD91B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。 也就是说这个代理是百度google翻译公用的，而我在config.json删除代理，并重启comfyui之后，仍然同样错误提示。我不得不重装插件，，，
> 
> 我在最新版本里面强制了百度的请求不用代理，你可以更新看看是否能解决问题。

非常感谢，辛苦啦，现在已经可以不用代理使用百度了。另外我看到命令行窗口还有一个无关紧要的提示：
[NYJY][2024-10-10 01:43:02][D:\ComfyUI\custom_nodes\ComfyUI_NYJY\nodes\utils.py, line: 41]: 没有查询到系统的代理

**Comment by vigee88** [comment]
> 这个问题我检查一下，正常来说，百度的域名不需要使用代理。感谢你的反馈。

今天更新了新版本，又变成百度翻译也需要代理了，不开代理用不了。。。
