### ISSUE TITLE
[Feature Request]: Support New Alpha One Version | [功能请求]: 支持新版 Alpha One 版本

### ISSUE THREAD

**Issue by Vigilence** [aidenli/ComfyUI_NYJY#9]
[功能请求]: 支持新版 Alpha One 版本

https://huggingface.co/spaces/fancyfeast/joy-caption-alpha-one

**Comment by aidenli** [comment]
Ok, I'll add it asap.

**Comment by aidenli** [comment]
ComfyUI_LayerStyle(https://github.com/chflame163/ComfyUI_LayerStyle/tree/main) already provides this function, so I won't reinvent the wheel. I provide an online calling node. The advantage is that you don't need to download jaycaotion alpha two, so you need llm and clip models, but the daily quota is limited.
